version: "3.8"

services:
  db:
    container_name: esp_db
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}",  "-d", "${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./esp_db:/var/lib/postgresql/data
  backend:
    container_name: esp_api
    build: .
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    entrypoint: >
      bash -c "alembic upgrade head
      && gunicorn -b 0.0.0.0:8000 -w 2 -k uvicorn.workers.UvicornWorker src.main:app"

volumes:
  esp_db:

networks:
  default:
    external:
      name: main_network
